server:
  port: 8081


spring:
  application:
    name: userservice

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  datasource:
    url: ${USERSERVICE_DB_URL}
    username: ${USERSERVICE_DB_USER}
    password: ${USERSERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  grpc:
    server:
      port: 9091
      reflection:
        enabled: true
      address: 0.0.0.0
