services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: authservice-db
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_LOGIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - authservice-db
    command:
      - "start-dev"
    networks:
      - discipline-app

  authservice-db:
    image: postgres:17-alpine
    container_name: authservice-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${AUTHSERVICE_DB_NAME}
      POSTGRES_USER: ${AUTHSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${AUTHSERVICE_DB_PASSWORD}
    volumes:
      - authservice_db_data:/var/lib/postgresql/data
    networks:
      - discipline-app

  userservice-db:
    image: postgres:17-alpine
    container_name: userservice-db
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/.env.userservice
    environment:
      POSTGRES_DB: ${USERSERVICE_DB_NAME}
      POSTGRES_USER: ${USERSERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USERSERVICE_DB_PASSWORD}
    volumes:
      - userservice_db_data:/var/lib/postgresql/data
    networks:
      - discipline-app

  userservice:
    container_name: userservice
    build:
      context: .
      dockerfile: userservice/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./secrets/.env.userservice
    environment:
      USERSERVICE_DB_URL: ${USERSERVICE_DB_URL}
      USERSERVICE_DB_USER: ${USERSERVICE_DB_USER}
      USERSERVICE_DB_PASSWORD: ${USERSERVICE_DB_PASSWORD}
    depends_on:
      - userservice-db
    networks:
      - discipline-app

#  authservice:
#    container_name: authservice
#    build:
#      context: .
#      dockerfile: authservice/Dockerfile
#    ports:
#      - "8082:8082"
#    env_file:
#      - .env
#      - ./secrets/.env.authservice
#    environment:
#      AUTHSERVICE_DB_URL: ${AUTHSERVICE_DB_URL}
#      AUTHSERVICE_DB_USER: ${AUTHSERVICE_DB_USER}
#      AUTHSERVICE_DB_PASSWORD: ${AUTHSERVICE_DB_PASSWORD}
#    depends_on:
#      - authservice-db
#    networks:
#      - discipline-app

volumes:
  userservice_db_data:
    driver: local
  authservice_db_data:
    driver: local

networks:
  discipline-app:
    driver: bridge