services:
  vault:
    image: hashicorp/vault:1.21
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: "http://127.0.0.1:8200"
    ports:
      - "8200:8200"
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - discipline-app

  vault-init:
    image: hashicorp/vault:1.21
    container_name: vault-init
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: ${VAULT_TOKEN}
    # Мы убрали 'secrets enable', так как в dev-режиме 'secret/' уже есть.
    # И записали всё в одну строку, чтобы избежать ошибки "not found".
    entrypoint: >
      sh -c "vault login $$VAULT_TOKEN && vault kv put secret/userservice spring.datasource.url='jdbc:postgresql://userservice-db:5432/userservice_db' spring.datasource.username='discipline-app-admin' spring.datasource.password='password'"
    networks:
      - discipline-app

  userservice:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    container_name: userservice
    environment:
      - VAULT_URI=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    env_file:
      - .env
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      vault-init:
        condition: service_completed_successfully
      userservice-db:
        condition: service_started
    networks:
      - discipline-app

  userservice-db:
    image: postgres:17-alpine
    container_name: userservice-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - discipline-app


networks:
  discipline-app:
    driver: bridge